### ISSUE TITLE
Be able to create google forms that submit data to nationbuilder

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/welcome#11]
This is maybe related to #3 or perhaps there is already a nationbuilder plugin that does this.  But I find that people constantly default to using Google Forms instead of Nationbuilder forms because they are easier to set up.  It would be nice if we could just use Google Forms and not have to copy data over.

**Comment by natmar** [comment]
Nationbuilder's import interface allows you to set tags as a column field when you import from sheets. It's probably a good idea to keep this manual as it provides a data validation check.

**Comment by saikat** [comment]
Yeah good point, though it would be nice if there was a plugin that does this automatically but is able to report on the validation checks (either via email or via UI that exists on a google sheet).  Removed the priority-high label though, as this hasn't been a big bottleneck for us now that we have a data entry team set up.

**Comment by rianhunter** [comment]
I can tackle this.

I don't have an understanding of NationBuilder's data model but I will do research and ask more questions as I understand the particular ins and outs of the problem.

Just to confirm, you're looking for a NationBuilder plugin, correct? I.e. not a separate hosted app that does this through the Google Forms/Sheets API and the NationBuilder API.

**Comment by rianhunter** [comment]
Just to make sure I'm looking in the right place, I assume this is the NationBuilder API I should be tinkering with: http://nationbuilder.com/surveys_api

I also couldn't find any info on building NationBuilder plugins. Any idea where I should look for that?

**Comment by rianhunter** [comment]
Just FYI I won't start on this until I get some confirmation! If there is another more well-defined task though more difficult I am open to doing that as well.

**Comment by saikat** [comment]
Sorry about that -- this task is probably not the most important thing to
take on anymore.  Any of the tasks in the website repo right now are a bit
more important.  Thanks!
