### ISSUE TITLE
Go through the process of getting a Nationbuilder API key

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/welcome#12]
They make us take a quiz and stuff.

**Comment by saikat** [comment]
@evanhl is taking this one.

**Comment by seanmacalways** [comment]
Just wanted to ask, are we committing to NationBuilder, or are we just using it until it becomes necessary to develop our own solution? I feel like it wouldn't be too hard, given the volunteer base BNC is garnering, to use [NationBuilder's free voter file request](http://nationbuilder.com/voterfile) in a coordinated fashion across many volunteers to essentially reconstitute a snapshot of the national database from which to start working.

**Comment by saikat** [comment]
We aren't even using nationbuilders voter file yet -- we are just using it
as a crm to manage our list, volunteers, tags, communication, etc. Not
committed to sticking with it though but we'd need a good alternative
(which is something I am trying to work on currently but it's a bit of a
longer term project).

I'm not sure we will be using nationbuilders voterfile once we start
campaigning (probably around early 2017). If you are interested in working
on the project to build an alternative to nationbuilder (which would also
be an alternative to VAN) I'd encourage you to join one of the other BNC
teams (eg call team or helpdesk) to get a sense of how nationbuilder works
and how we are using it.

**Comment by evanhl** [comment]
Just submitted completed exercises. Hopefully they'll grant me access soon.

**Comment by evanhl** [comment]
They finally got back to me on Friday, saying there was an issue with the scripts I sent in. I don't have a sandbox account or anything to test with, so I was flying somewhat blind with the NB exercises. I requested a sandbox, but they haven't gotten back yet.

**Comment by evanhl** [comment]
This is blocking: https://github.com/BrandNewCongress/dashboard/issues/5

**Comment by evanhl** [comment]
I was able to get a sandbox environment from NB and fix the issues. I resubmitted just now. _fingers crossed_

**Comment by AlaskanOracle** [comment]
Has anyone looked at or thought of using CiviCRM (http://www.civicrm.org) SAAS kinda scares me personally , a good example of the is back in December when the DNC cut off Bernie's Access to VAN

**Comment by saikat** [comment]
We have some folks on who have used CiviCRM in the past and decided to go
with Nationbuilder for now.  We think it should be fine - Nationbuilder is
more of an independent business, but we are going to be backing up our data
periodically to play it safe.

**Comment by evanhl** [comment]
NB accepted the exercises, and I now have developer access.

**Comment by saikat** [comment]
Huzzah!

**Comment by evanhl** [comment]
I created a new NB app for the Dashboard called BNC Dashboard. You can see it here. There's no actual OAuth callback URL yet, so I filled in a fake, but at least we have a client secret and token we can play around with: https://brandnewcongress.nationbuilder.com/admin/apps/575af272566f8f0d00000003/
