### ISSUE TITLE
AUTHORS

### ISSUE THREAD

**Issue by dv8silencer** [BrandNewCongress/welcome#13]
I know this is supposed to be open source.  If that is the case... will you respect contributors/engineers/authors and at least have an AUTHORS file?  This is basic for almost all projects.  I know C, C++, javascript, CSS, HTML, PHP, CUDA, TCL, but appropriate attribution is **VERY** important.

**Comment by saikat** [comment]
Yes, I agree that attribution is incredibly important. Would you like to
take a shot at adding an authors file generation script to the project?
That's probably the best way to ensure we keep the authors file up to date.

**Comment by saikat** [comment]
@dv8silencer Any chance you would like to add this and add a script for us to keep the Authors files up to date based on github contributors?

**Comment by dv8silencer** [comment]
Not very familiar regarding authors script but I will look into it.  Thanks!
