### ISSUE TITLE
www.brandnewcongress.com/teams LINK NEEDS TO BE ADDED ASAP

### ISSUE THREAD

**Issue by benisch2** [BrandNewCongress/welcome#16]
There is no link to get to www.brandnewcongress.com/teams from the main website at www.brandnewcongress.com.

I only just found out about it now because a pollworker called and told me about it. I don't know who's in charge of the website, but it would be trivial to add it, and it would really help us in finding people to volunteer! I've gone to the website many times but only found links to physical gatherings.

This needs to be done as soon as possible.

**Comment by traviskaufman** [comment]
Hey @benisch2 thanks for filing! I copied this issue over to https://github.com/BrandNewCongress/website at https://github.com/BrandNewCongress/website/issues/68 which is the github repository where we track all issues/requests around brandnewcongress.com. We can continue the conversation over there. Thanks!
