### ISSUE TITLE
Create a Congressional District map interface on top of Airtable

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/welcome#26]
We would want to use this, at least at first, to map the number of candidates we have per district in each round of vetting. But I can also imagine using it for events, visualizing offices, etc.

**Comment by codygordon** [comment]
I'm going to give this a stab. Spoke to @saikat on Slack today, and want to memorialize what we discussed.

Thinking of a non-geographically perfect map, but more of a "honeycomb" style scaled map using SVG assets, i.e. 
http://images.dailykos.com/images/146447/story_image/Intro1.png?1433269941
with interactivity like: https://projects.fivethirtyeight.com/2016-election-forecast/#electoral-map

I'd also like to demo a version using the [MapBox GL API](https://www.mapbox.com/mapbox-gl-js/api/), perhaps giving users an option to toggle between the two? 

The kinds of things we’d like to visualize are:

1) Number of nominations per district.  Heat map + if you click on a district, it shows the exact number
2) Number of nominations that have made it to round 4 of vetting in each district 
3) Number of volunteers in each district (that would be reading from nationbuilder though, which is a different API from Airtable)

MVP can be a standalone React app allowing csv upload of data. For API integration, will explore GraphQL / Apollo. 

Later, potential to integrate https://github.com/BrandNewCongress/welcome/issues/23, i.e. the main interface would be the map, and then clicking into a district would show you info about the district such as qualitative and quantitative info.

**Comment by saikat** [comment]
Moved to its own project.
