### ISSUE TITLE
Figure out an architecture for using shared tools but across differently styled sites

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/welcome#30]
Currently we have a lot of shared resources between JD and BNC, but in the future we will have lots of shared resources across hundreds of candidates who may all have different websites.  How do we do it?

**Comment by ghost** [comment]
You're going to have a ton of platforms being used by nominees, candidates, contributors, staff, lead generators, even social media. You need to decide what data you want/need and if you need it real time. You will likely run into websites or systems that aren't able to, or willing to integrate and share data - so how is that handled? That's just one minor obstacle. 

The fact that you use NationBuilder means you're already off to a great start and can begin working on some of the larger integrations right off the bat without much thought. Here's a couple ways to start: 

> 1. Integrate existing apps to gather and share data: http://nationbuilder.com/integrations
> 2. Create new apps: http://nationbuilder.com/developers

This needs a more in depth integration documentation including some research and development. I'm willing to spearhead this as a main project- but I'd need to speak with the people who want and need these resources and data, as well as those who will have access to it to see what everyone needs to have from UI to access.

Let's connect at some point to discuss further - as I'd need access to the core of NationBuilder to set up a sandbox and begin working on this.

**Comment by saikat** [comment]
The data question is addressed in a different issue - #28 

We actually came up with an answer to this using a multi-site CRM that Chad Meyer on the team has.  Thanks though!
