### ISSUE TITLE
Dashboard refresh

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/welcome#34]
We'd like to create a new BNC dashboard/work tracking system.  The idea is to track some topline metrics (similar to the ones we already have on dashboard.brandnewcongress.org) and then we also need to track:
* Metrics per team
* Metrics per squad
* Goals per team
* Possibly have a manual way to submit metrics for metrics we can't grab automatically

Here's a mockup of what it could look like - https://gomockingbird.com/projects/k7skgqd/KAdwbO

**Comment by traviskaufman** [comment]
I can take a crack at this. I'd need access to the dashboard as well as the potential data sources (mock data is fine as long as I have something to work with)

**Comment by saikat** [comment]
Awesome, I'll do this tonight.  One idea I just had -- we could maybe just use something like datadog (which we used in Bernie to make custom dashboards).

**Comment by traviskaufman** [comment]
That sounds like a great idea. I used DD at a previous job to track
metrics. IIRC it was relatively limited in some respects but if it suits
the needs of the dashboard it would definitely be a fast path towards a
solution

**Comment by traviskaufman** [comment]
Was talking to @brockoffdev today about this and he mentioned [Prometheus](https://prometheus.io/), which can do metrics as well as alerting and can be integrated with grafana or plugged into any pre-existing dashboard. May be worth looking into as well.
