### ISSUE TITLE
Add a press@ e-mail address

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/welcome#36]

**Comment by danielameyer** [comment]
I already added them to the footer on both sites.

**Comment by danielameyer** [comment]
And the mobile sidebar on JD, should probably add to the mobile sidebar on BNC?

**Comment by danielameyer** [comment]
I added that to both sites yesterday—to the footer. I also added it to the mobile sidebar on JD. Should probably add it to the mobile sidebar on BNC. The one I already added to the footer won't be live until Chad pushes his changes and mine to the live server all at once.

**Comment by danielameyer** [comment]
Oh weird, github said there were no comments so I retyped it all.

**Comment by ben-pr-p** [comment]
This seems closed, @danielameyer ?
