### ISSUE TITLE
Research Tech and Implementation

### ISSUE THREAD

**Issue by traviskaufman** [BrandNewCongress/welcome#39]

**Comment by traviskaufman** [comment]
cc @brockoffdev

**Comment by brockoffdev** [comment]
@traviskaufman here

**Comment by saikat** [comment]
Should we turn this into a repo and start adding issues there?

**Comment by brockoffdev** [comment]
@saikat we're spec-ing out the project; once we have a firmer idea of what our implementation we'll ask for a repo.
