### ISSUE TITLE
Create an org chart that updates dynamically based on our org in airtable

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/welcome#44]

**Comment by jord8on** [comment]
Hello, @saikat - We are using Airtable for our Employee Directory but would love to see an Org Chart view. Can you point me in the direction of more information about how to do this?

**Comment by saikat** [comment]
@jord8on I believe @ben-pr-p made https://github.com/BrandNewCongress/org-chart to do this.

**Comment by jord8on** [comment]
Thank you @saikat!

@ben-pr-p do you have any layman instructions on how to leverage your tool? Do you have any screenshots or images of this, in action?
